### ISSUE TITLE
New Arch build fails on iOS 'RNRootViewBackgroundSpec.h' file not found

### ISSUE THREAD

**Issue by efstathiosntonas** [pnthach95/react-native-root-view-background#2]
Hi, I'm getting this issue when using the new arch: 

`'RNRootViewBackgroundSpec.h' file not found`
![Screenshot 2023-08-05 at 11 35 44](https://github.com/pnthach95/react-native-root-view-background/assets/717975/02dec20b-113b-43fe-b871-70d1df37ec5e)

react-native 0.72.3, xcode 14.3.1

**Comment by pnthach95** [comment]
I published v1.4.0 to support new arch. However, while testing android new arch with example, after navigated to new screen, I can't press any buttons. Maybe it just something was wrong with my example. Help me test it.

EDIT: just tried without my package, the issue still happens, so my package is safe to use

Reopen if you have problem with latest version
