### ISSUE TITLE
Getting 'RCTRequired/RCTRequired.h' file not found issue.

### ISSUE THREAD

**Issue by Gautham495** [pnthach95/react-native-root-view-background#5]
<img width="1265" alt="Screenshot 2024-11-11 at 11 36 01 PM" src="https://github.com/user-attachments/assets/4e1a95f2-fac3-4e25-aa12-1354093c9938">

I have attached the screenshot.

@pnthach95 - This is for old arch and runs in 73.8.

**Comment by Gautham495** [comment]
Version is 1.4.8

**Comment by pnthach95** [comment]
Retry with version 1.4.3

**Comment by Gautham495** [comment]
It works with 1.4.3

**Comment by pnthach95** [comment]
I wrote note about it in README. Look like these codegen files aren't compatible with older RN versions
